### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zgreat** [metalicjames/CryptoKernel#1]
In this branch will nodes sync and mine the same blocks or create new blocks when syncing from peers like the master branch?

**Comment by metalicjames** [comment]
Hi, which branch do you mean exactly? The one from mit-dci?

**Comment by Mast3rMind** [comment]
Yeah master from mit-dci

**Comment by metalicjames** [comment]
Well the branch in this fork doesn't currently have a working network class but supports Lua smart contracts so won't sync with the master from mit-dci. I will push it there once the network is working.

**Comment by Mast3rMind** [comment]
Okay thanks
