### ISSUE TITLE
Ckd crashes syncing blocks 2568 to 2768

### ISSUE THREAD

**Issue by zgreat** [metalicjames/CryptoKernel#3]
./ckd
Tue Jun 13 22:49:56 2017 INFO CryptoKernel version 11.0.0-dev started
Tue Jun 13 22:49:57 2017 INFO Network(): Attempting to connect to 18.189.14.111
Tue Jun 13 22:50:17 2017 INFO miner(): Hashrate: 26.165 kH/s
Tue Jun 13 22:50:21 2017 WARNING Network(): Failed to connect to 18.189.14.111
Tue Jun 13 22:50:21 2017 INFO Network(): Attempting to connect to 18.238.7.30
Tue Jun 13 22:50:21 2017 INFO Network(): Successfully connected to 18.238.7.30
Tue Jun 13 22:50:21 2017 INFO Network(): Attempting to connect to 18.85.34.112
Tue Jun 13 22:50:22 2017 WARNING Network(): Failed to connect to 18.85.34.112
Tue Jun 13 22:50:22 2017 INFO Network(): Attempting to connect to 198.204.233.155
Tue Jun 13 22:50:22 2017 INFO Network(): Successfully connected to 198.204.233.155
Tue Jun 13 22:50:22 2017 INFO Network(): Attempting to connect to 52.55.99.192
Tue Jun 13 22:50:22 2017 INFO Network(): Successfully connected to 52.55.99.192
Tue Jun 13 22:50:23 2017 INFO Network(): Current height: 2567, best height: 5014
Tue Jun 13 22:50:23 2017 INFO Network(): Downloading blocks 2568 to 2768
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load lz4
Aborted (core dumped)

Using Ubuntu bash on Windows 10
**Pulled from master after peer discovery implementation and fixes**

**Comment by metalicjames** [comment]
Hey, do you have an lz4.dll file in the same directory as ckd? If you explore the installdeps.sh script you should see how it is created there. If it proves too difficult to build I have a binary for lz4 that I have attached.
[lz4.zip](https://github.com/metalicjames/CryptoKernel/files/1073388/lz4.zip)

**Comment by zgreat** [comment]
I was able to build it and it fixed the issue cheers!
I figured the installdeps.sh script would install everything needed
